#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_I2C_SDA_GPIO       8
#define APP_I2C_SCL_GPIO       10
#define APP_I2C_FREQUENCY_HZ   400000
#define APP_IMU_I2C_ADDRESS    0x68
#define APP_SAMPLE_PERIOD_MS   1000
#define APP_CALIBRATION_SAMPLES 100
#define APP_CALIBRATION_PERIOD_MS 20
#define APP_FILTER_ALPHA       0.30f
#define APP_MOTION_EVAL_PERIOD_MS 100
#define APP_MOTION_ACCEL_ENTER_G 0.20f
#define APP_MOTION_ACCEL_CLEAR_G 0.10f
#define APP_MOTION_GYRO_ENTER_DPS 8.0f
#define APP_MOTION_GYRO_CLEAR_DPS 3.0f
#define APP_MOTION_ENTER_SAMPLES 4
#define APP_MOTION_CLEAR_SAMPLES 1
#define APP_EVENT_ACCEL_THRESHOLD_G 0.30f
#define APP_EVENT_ACCEL_CONFIRM_SAMPLES 2
#define APP_EVENT_CORNER_ACCEL_THRESHOLD_G 0.25f
#define APP_EVENT_CORNER_GYRO_THRESHOLD_DPS 12.0f
#define APP_EVENT_CORNER_CONFIRM_SAMPLES 2
#define APP_EVENT_IMPACT_GYRO_THRESHOLD_DPS 20.0f
#define APP_EVENT_IMPACT_GYRO_DELTA_DPS 10.0f
#define APP_EVENT_IMPACT_GYRO_RECOVERY_DPS 8.0f
#define APP_EVENT_IMPACT_GYRO_AXIS 2
#define APP_EVENT_IMPACT_WINDOW_MS 500
#define APP_EVENT_HOLD_MS 1000
#define APP_EVENT_CLEAR_SAMPLES 3
#define APP_EVENT_HISTORY_SAMPLES 5
#define APP_EVENT_CORNER_GYRO_AXIS 2
#define APP_EVENT_IMPACT_CONFIRM_SAMPLES 1
#define APP_WIFI_SSID "drivesense"
#define APP_WIFI_PASSWORD "25092002"
#define APP_TCP_STATUS_PORT 5000
#define APP_WIFI_RETRY_DELAY_MS 5000
#define APP_EVENT_GENERIC_ACCEL_THRESHOLD_G 0.20f
#define APP_EVENT_GENERIC_GYRO_THRESHOLD_DPS 8.0f
#define APP_EVENT_GENERIC_CONFIRM_SAMPLES 4

#endif
