#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_I2C_SDA_GPIO       8
#define APP_I2C_SCL_GPIO       10
#define APP_I2C_FREQUENCY_HZ   400000
#define APP_IMU_I2C_ADDRESS    0x68
#define APP_SAMPLE_PERIOD_MS   1000
#define APP_CALIBRATION_SAMPLES 100
#define APP_CALIBRATION_PERIOD_MS 20
#define APP_FILTER_ALPHA       0.30f
#define APP_MOTION_EVAL_PERIOD_MS 100
#define APP_MOTION_ACCEL_ENTER_G 0.20f
#define APP_MOTION_ACCEL_CLEAR_G 0.10f
#define APP_MOTION_GYRO_ENTER_DPS 8.0f
#define APP_MOTION_GYRO_CLEAR_DPS 3.0f
#define APP_MOTION_ENTER_SAMPLES 4
#define APP_MOTION_CLEAR_SAMPLES 1

#endif
