#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_I2C_SDA_GPIO       8
#define APP_I2C_SCL_GPIO       10
#define APP_I2C_FREQUENCY_HZ   400000
#define APP_IMU_I2C_ADDRESS    0x68
#define APP_SAMPLE_PERIOD_MS   1000
#define APP_CALIBRATION_SAMPLES 100
#define APP_CALIBRATION_PERIOD_MS 20
#define APP_FILTER_ALPHA       0.20f

#endif
